/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Course {
  'id' : bigint,
  'title' : string,
  'duration' : number,
  'thumbnailUrl' : string,
  'difficulty' : string,
  'description' : string,
  'instructorId' : [] | [bigint],
  'category' : string,
  'price' : number,
  'modules' : Array<CourseModule>,
}
export interface CourseModule {
  'id' : bigint,
  'title' : string,
  'description' : string,
}
export interface Enquiry {
  'id' : bigint,
  'name' : string,
  'submittedAt' : bigint,
  'email' : string,
  'message' : string,
  'phone' : string,
  'courseInterested' : string,
}
export interface Instructor {
  'id' : bigint,
  'bio' : string,
  'name' : string,
  'expertise' : Array<string>,
  'avatarUrl' : string,
}
export interface Testimonial {
  'userId' : Principal,
  'comment' : string,
  'rating' : bigint,
  'courseId' : bigint,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addTestimonial' : ActorMethod<[bigint, bigint, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCourse' : ActorMethod<
    [
      string,
      string,
      string,
      [] | [bigint],
      Array<CourseModule>,
      string,
      number,
      string,
      number,
    ],
    bigint
  >,
  'createInstructor' : ActorMethod<
    [string, string, Array<string>, string],
    bigint
  >,
  'deleteCourse' : ActorMethod<[bigint], undefined>,
  'deleteEnquiry' : ActorMethod<[bigint], undefined>,
  'deleteInstructor' : ActorMethod<[bigint], undefined>,
  'enrollInCourse' : ActorMethod<[bigint], undefined>,
  'getAllCourses' : ActorMethod<[], Array<Course>>,
  'getAllEnquiries' : ActorMethod<[], Array<Enquiry>>,
  'getAllInstructors' : ActorMethod<[], Array<Instructor>>,
  'getAllTestimonials' : ActorMethod<[], Array<Testimonial>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCourseById' : ActorMethod<[bigint], [] | [Course]>,
  'getCourseCategories' : ActorMethod<[], Array<string>>,
  'getCourseProgress' : ActorMethod<[bigint], number>,
  'getEnrolledCourses' : ActorMethod<[], Array<bigint>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markModuleCompleted' : ActorMethod<[bigint, bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitEnquiry' : ActorMethod<
    [string, string, string, string, string],
    bigint
  >,
  'updateCourse' : ActorMethod<
    [
      bigint,
      string,
      string,
      string,
      [] | [bigint],
      Array<CourseModule>,
      string,
      number,
      string,
      number,
    ],
    undefined
  >,
  'updateInstructor' : ActorMethod<
    [bigint, string, string, Array<string>, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];